### ISSUE TITLE
GFSQuery .reset() Dead loop

### ISSUE THREAD

**Issue by OlejonSwift** [imperiumlabs/GeoFirestore-iOS#15]
xCode 10.1, Swift 4.2.

There's property 'queries' of type Set<GFGeoHashQuery> in GFSQuery class.
In "reset()" function iterating through elements in for loop when marking element as optional leads to dead lock. 
As i can see there's no need to mark them as optional because Set< GFGeoHashQuery> can't contain nil. Simply removing '?' will fix the issue.

BTY. Interesting, this dead lock can be reproduced in playground with just 4 lines:
var queries = Set< String >()
for query: String? in queries {
    print(query ?? "")
}

**Comment by progn** [comment]
I've got the same issue, fixed it in my PR
