### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":

### ISSUE THREAD

**Issue by eren-celik** [imperiumlabs/Geofirestore-ios#37]
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In snapshot (Podfile.lock):
    FirebaseCore (= 6.9.1, ~> 6.8)

  In Podfile:
    Firebase/Firestore was resolved to 6.28.1, which depends on
      Firebase/CoreOnly (= 6.28.1) was resolved to 6.28.1, which depends on
        FirebaseCore (= 6.9.1)

    Firebase/Firestore was resolved to 6.28.1, which depends on
      FirebaseFirestore (~> 1.16.2) was resolved to 1.16.2, which depends on
        FirebaseCore (~> 6.8)

    Geofirestore was resolved to 0.1.0, which depends on
      FirebaseCore (~> 5.0.3)

pls help me

**Comment by RonithK** [comment]
I'm getting the same error, let me know if you were able to figure this out

**Comment by eren-celik** [comment]
its too easy you only to do 

  use_frameworks!

line

**Comment by bcartin** [comment]
Hi erenlk,

I'm having the same issue, were you able to fix this? What exactly do you need to do with the use_frameworks line?

thanks

**Comment by eren-celik** [comment]
#16 
Here is the sample PodFile




Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'your_appName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GeoFire', '~> 4.0'
pod 'SDWebImage'

  # Pods for your_appName

end

**Comment by sgallo0692** [comment]
@bcartin were you able to fix this? stuck on this right now, not sure what the dependency problem is

**Comment by bcartin** [comment]
> @bcartin were you able to fix this? stuck on this right now, not sure what the dependency problem is

@sgallo0692 Yes I did. imperiumlabs never fixed the issue but someone else did. Use this in your pod file instead:

pod 'Geofirestore', :git => 'https://github.com/patpatchpatrick/GeoFirestore-iOS'

all credit goes to patpatchpatrick

**Comment by sgallo0692** [comment]
@bcartin hey thanks for the response, actually also found patpatchpatrick's fork as well and got it loaded up successfully. looks like our only option for now. thanks again
